In [87]:
import torch
import torchvision


a = torch.randn(6,19,19)
b = torch.randn(6,5,5)
# print(a)
# print(b)
res = torch.nn.Conv2d(6, 6, 3, stride=1, padding=0)(a)
print(res.shape)

torch.Size([6, 17, 17])


In [54]:
x = torch.randn(123,1)
x

tensor([[-0.4328],
        [ 0.7639],
        [ 1.2974],
        [-0.1785],
        [-0.7232],
        [-0.3632],
        [ 0.3054],
        [-0.2556],
        [-0.9398],
        [-0.5263],
        [-1.4387],
        [-0.0974],
        [ 0.8706],
        [-0.7042],
        [ 0.3527],
        [-1.4179],
        [-0.3466],
        [ 0.2472],
        [-0.3612],
        [ 0.3329],
        [ 0.5138],
        [-0.5081],
        [-0.2075],
        [-1.0698],
        [-0.0170],
        [ 0.2761],
        [ 0.6707],
        [ 0.2465],
        [-0.9350],
        [ 0.2049],
        [-1.0691],
        [-1.3093],
        [ 0.1026],
        [-1.5192],
        [-0.5678],
        [-1.7483],
        [-0.8430],
        [ 1.7209],
        [ 0.1627],
        [ 0.9258],
        [-0.4958],
        [ 0.6156],
        [ 0.8023],
        [-0.6862],
        [-1.3833],
        [ 0.0265],
        [-1.2795],
        [ 0.7875],
        [ 2.1276],
        [ 0.1261],
        [-0.7938],
        [ 0.1950],
        [ 1.

In [52]:
torch.nn.ReLU(inplace=True)(x)

tensor([[[0.0000e+00, 7.9515e-01, 2.6115e-01, 5.5318e-01],
         [0.0000e+00, 0.0000e+00, 1.5683e+00, 1.1952e+00],
         [0.0000e+00, 0.0000e+00, 7.5528e-01, 1.2436e+00]],

        [[0.0000e+00, 0.0000e+00, 7.6358e-01, 5.6140e-01],
         [0.0000e+00, 0.0000e+00, 3.5694e-01, 0.0000e+00],
         [1.9251e+00, 0.0000e+00, 1.1126e+00, 1.6761e-03]]])

In [53]:
x

tensor([[[0.0000e+00, 7.9515e-01, 2.6115e-01, 5.5318e-01],
         [0.0000e+00, 0.0000e+00, 1.5683e+00, 1.1952e+00],
         [0.0000e+00, 0.0000e+00, 7.5528e-01, 1.2436e+00]],

        [[0.0000e+00, 0.0000e+00, 7.6358e-01, 5.6140e-01],
         [0.0000e+00, 0.0000e+00, 3.5694e-01, 0.0000e+00],
         [1.9251e+00, 0.0000e+00, 1.1126e+00, 1.6761e-03]]])